{%set name = "shutilwhich" %}
{%set version = "1.1.0" %}
{%set compress_type = "tar.gz" %}
{%set hash_type = "sha256" %}
{%set hash_val = "db1f39c6461e42f630fa617bb8c79090f7711c9ca493e615e43d0610ecb64dc6" %}
{%set build_num = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  number: {{ build_num }}
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip

  run:
    - python

test:
  imports:
    - shutilwhich

about:
  home: http://github.com/mbr/shutilwhich
  license: PSF 2
  # license_file: No LICENSE or MANIFEST.in - see https://github.com/mbr/shutilwhich/issues/2
  license_family: PSF
  summary: 'shutil.which for those not using Python 3.3 yet.'
  dev_url: http://github.com/mbr/shutilwhich

extra:
  recipe-maintainers:
    - pmlandwehr
