travis:
  secure:
    BINSTAR_TOKEN: BZHaPaGwqLNFSNUu1R3B1f1ZKs/MV9kChA/k8lq24LMZaUgY86aV0F0skftrCDM+8uwv3L+VLrtqe2HNN2raMmrOo5ow9a7Ffcd/83D1RiKIr7tBk0Q/BhDtWtwfKpTOeDV1Ww5u+3Bhx6pAANU+iqkOi/f9r2LD9Vhp+7sRPajl0M28c4xc9uTsIClo9ReiGDpbi22k4S5IwAGLI0Hp4fLWEGMtIevjYS6k5TjOGRCs8/uabGISxicXUn1qgYH4v2J4j0ugylfT/U0ulR3kLmCItPiw5GziCMD5MZ1EFAaRYV8qQ6jMU6w/F9s60ZBk/UYyp0Uajho1Aji6YytO+aryB9wj6ZYOfgUh4oIoUfxTm5OxUzuGBxbzPK8e2gQnx+djQcTz5QfBf2PWRZrMA7bgTlE4E/yPQpzElIPPfVPlse4+uHJtKvSitrFRWpdYsLIzkVUEqyiYA0ELHZDvmk/g7zUz/GH54YvC2Tu6rfur6sK2wzFGxWXiTuzRNZHVKkZb9mpqGaS9BWO6iUtCrYSbwAZlB775jZ6okoKM4fr2mGsB2mYYEZYtmFW6aJHFhNSTDfHDNTU6MbJ89s6vWVeOZ7BALEfImNVD87sctAvbSBkJ2GJFWNvwagV/NKzXLcR5MIn5KOeBucbUW3g5Itu4a0J162Rwyxr+TRsarP0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
