travis:
  secure:
    BINSTAR_TOKEN: OyXlZBGTp1YEtlMNPE2eNU9p1Mj+cKu0TcGcVFH8FXsTW9vLHIxXAooSItb+D6hr883GQZFwgUvZNOeFoD/jBj6usVlCUJ+6wU9lB/6/sMSSdiJnD9nModb6+nyjIuow1MJysOXUw/VhHiZXESoRgBgY985hTtTmnCSqEpzmlg1t7R1KqVF6tXPs40xYjr9fMD+dbeA+CnXRe+mQMTA26RLJDDc38XUYJNFBaArxRgNtLSXFL/pVNLHTQmnAZJtFrK9w55+gxxCv0ky5R4wnY1yHd/TterXR+gAWtUP/j4+KYKND7T+dWoUXgRhO4eDyBG5qHemHuSxYQasWfSKZnIv4RNn2XDls4zLZKAZg6UR2fiSK6YMEwL9KKVfBPzEhDyH2BIebFOIYodedyyJ6V+DoYpXLnEnzTIaUoCzqEsiIKojD88lu+noIoyi1kAOelXHXEHVr3tK1Eh2JHx799xpRIRTuJTKJvnicHqv7AyKo/B9wBAxGNrlw4kTrExrn0/IVg+pW0wCivGrUletv/DYgWXr/7DlWi5YXnMNufAKxwf8m8UAzPFVTMpQB+HokLJBAxoHJBgTDzAxXMMu1zEHAFPkeRt28w5ZggxTdsmBEEcUgJ0NhyjOfGq1C5hOQem106fptbvGaEtbvqKPFd7//tYjnaIOnbFMnXvXmEeU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
